codecov:
  token: 490528ab-a1de-4b5e-80c7-5d95042b5376
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default
  require_changes: no

