# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
    include:
      - python: 3.6
        env: TOX_ENV=flake8
      - python: 3.7
        dist: xenial
        sudo: true
        env: TOX_ENV=flake8


install:
  - pip install tox

script:
  - tox -e $TOX_ENV
  - tox -e codecov

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
